version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - jroehl
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
